from app.graph.State import State, AgentState
from app.graph.llm import llm
from langchain_core.messages import AIMessage
from langchain.agents import create_agent
from langchain.tools import tool

prompt= """
You are a RAG agent.

Your main task is to handle plans that need stored personal, project, career, skills, or background knowledge from the RAG knowledge base.

First understand the user request and conversation history. Then call read_plan to see the current plan status.

If you find a pending plan that belongs to RAG, solve it using rag_fetcher. After solving it, call write_plan with the same plan text and status "completed".

If there are more pending RAG plans, you may read plans again and continue the same flow.

Do not solve weather or web-search plans.

If there are no plans, or if all plans are already completed, or if the only pending plans belong to other agents, then your work is done from the RAG side. In that case, look at the conversation history and prepare the best clean response you can for the final agent. If the user still needs stored personal/project knowledge, you may call rag_fetcher before responding.

After completing your work, your final response must summarize all useful retrieved information you produced. Do not include tool-call narration.
"""

def rag(state: State):
    print("📚 RAG node entered")
    from app.graph.tools.rag import rag_fetcher
    plans = state["plans"]

    @tool
    def read_plan():
        """use this tool to read all plan generated by supervisor agent"""
        print(f"📖 RAG reading plan: {plans}")
        if len(plans.keys()) == 0:
            return "There are no todo plans as of now, please respond with normally"
        return plans

    @tool
    def write_plan(plan: str, status: str):
        """use this tool to write all plan generated by supervisor agent"""
        print(f"✍️ RAG writing plan status: {plan} -> {status}")
        plans[plan] = status
        return "plans written successfully"

    agent = create_agent(
        model=llm,
        system_prompt=prompt,
        tools=[rag_fetcher, read_plan, write_plan]
    )
    response = agent.invoke({"messages":state["messages"]})
    agent_response = response["messages"][-1].content
    agentHouse = state["agents"][0]
    agentHouse["rag"] = True
    print("✅ RAG node completed")
    return {
        "rag":[AIMessage(content=agent_response)],
        "plans": plans,
        "agents": [agentHouse]
    }
